package com.example.cmmsApplication.common.response;

public enum ApiErrorCode {
    SUCCESS,
    VALIDATION_ERROR,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RECORD,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_SERVER_ERROR,
    DATABASE_ERROR,
    FILE_UPLOAD_ERROR,
    INVALID_TOKEN,
    TOKEN_EXPIRED
}
