# Development profile

cmms.cors.allowed-origin-patterns=*
cmms.cors.allow-credentials=true
cmms.openapi.server-url=/api
cmms.openapi.server-description=Development API

logging.level.com.example.cmmsApplication=DEBUG
logging.level.org.springframework.security=DEBUG
